### ISSUE TITLE
locate/ru

### ISSUE THREAD

**Issue by MikdadAgasiev** [InappropriatePenguin/ghost-counter#1]
[mod-setting-name]
ghost-counter-min-update-interval=Минимальный интервал обновления.

[mod-setting-description]
ghost-counter-min-update-interval=Минимальное количество тиков между обновлениями данных мода. Меньшие цифры позволяют пользовательскому интерфейсу мода обновляться чаще. Увеличьте это число, если вы хотите свести к минимуму любое влияние на производительность. Значение по умолчанию: 10 [5-120].

[shortcut]
make-ghost-counter=Счетчик чертежей (блюпринтов).

[controls]
ghost-counter-selection-hotkey=Активировать счетчик чертежей (блюпринтов).

[item-name]
ghost-counter-tool=Инструмент выбора счетчика чертежей.

[ghost-counter-message]
failed-to-clear-cursor=Не удалось очистить курсор.
crafts-attempted-none=Не удалось создать предмет.
crafts-not-needed=Без дополнительного крафта.
missing-constant-combinator-prototype=Не удалось найти константу-комбинатор в прототипах игровых сущностей.

[ghost-counter-gui]
cancel-all-tooltip= Отменить все временные логистические запросы.
close-button-tooltip=Закрыть окно.
existing-logistic-request-tooltip=Существующий логистический запрос соответствует требованиям.
get-signals-tooltip=Экспортировать чертеж считается сигналом.
hide-empty-requests-tooltip=Переключить скрытие строки, в которых не осталось чертежей.
craft-all-tooltip=Попытка создать все недостающие элементы.
request-all-caption=Запросить все.
request-all-tooltip=Создать временные логистические запросы для всех отсутствующих элементов.
set-temporary-request-tooltip=__CONTROL_LEFT_CLICK__ чтобы создать временный логистический запрос для __1__ __2__\n__CONTROL_KEY_SHIFT____CONTROL_STYLE_BEGIN__ + __CONTROL_STYLE_END____CONTROL_LEFT_CLICK__ для крафта
unset-temporary-request-tooltip=__CONTROL_LEFT_CLICK__ чтобы отменить временный логистический запрос\n__CONTROL_KEY_SHIFT____CONTROL_STYLE_BEGIN__ + __CONTROL_STYLE_END____CONTROL_LEFT_CLICK__ для крафта

**Comment by InappropriatePenguin** [comment]
Thanks for your contribution—your translation will be part of the next release :)
